---
name: Primi passi con Arduino
description: Installazione e configurazione dell'IDE Arduino
image: http://i.ebayimg.com/00/s/MTYwMFgxNjAw/z/0YEAAOxy9X5TbMG6/$_12.JPG
tags:
- arduino
- primi passi
- kit