name: Servotermometro
description: Costruire un termometro con il servomotore e il sensore DS18B20
image: http://projects.ebmstore.it/images/servo-temperature/3.jpg
tags: !!seq [ starter_kit, arduino ]
published: true